const copy = {
  ar: {
    appName: "تقفيلة",
    restaurant: "مشويات المعلم الشامي",
    employee: "موظف",
    staffBadge: "موظف",
    owner: "مالك",
    home: "الرئيسية",
    entries: "الإدخالات",
    settings: "الإعدادات",
    reports: "التقارير",
    attachments: "المرفقات",
    active: "نشط",
    openEntry: "مفتوح للإدخال",
    todayEntries: "إدخالات اليوم",
    enterDailySummary: "إدخال ملخص اليوم",
    addPurchaseExpense: "إضافة مشتريات / مصروف",
    amountNoteOptionalPhoto: "مبلغ + ملاحظة + صورة اختيارية",
    recentEntries: "آخر الإدخالات",
    viewAll: "عرض الكل",
    register: "السجل",
    ownerNotebook: "دفتري",
    ownerNotebookAdd: "إضافة للدفتر",
    ownerNotebookTask: "مهمة",
    ownerNotebookNote: "ملاحظة",
    ownerNotebookEmpty: "لا توجد ملاحظات بعد. ابدأ بدفترك الخاص.",
    ownerNotebookPlaceholder: "اكتب ملاحظة أو مهمة…",
    ownerNotebookHint: "ملاحظاتك الخاصة — لا يراها الموظفون.",
    ownerNotebookActive: "نشط",
    ownerNotebookAll: "الكل",
    ownerNotebookTasks: "مهام",
    ownerNotebookNotes: "ملاحظات",
    ownerNotebookDone: "منجزة",
    ownerNotebookNew: "إضافة جديدة",
    ownerNotebookPrivate: "خاص · للمالك فقط",
    ownerNotebookItems: "عناصر",
    ownerNotebookEmptyCta: "اضغط «إضافة جديدة» لتسجيل أول ملاحظة أو مهمة.",
    ownerNotebookSharePreview: "معاينة ملاحظة الدفتر",
    ownerNotebookShare: "مشاركة",
    ownerNotebookTaskTitle: "عنوان المهمة (اختياري)",
    ownerNotebookAddItem: "إضافة بند",
    ownerNotebookItemPlaceholder: "اكتب بندًا…",
    loading: "جاري التحميل…",
    operationsLog: "سجل العمليات",
    myEntries: "إدخالاتي",
    activeEntries: "نشطة",
    withAttachment: "بمرفق فقط",
    allTypes: "كل الأنواع",
    noOperationsMatch: "لا توجد عمليات مطابقة للفلاتر المحددة.",
    logPurpose: "كل إدخال محفوظ كسجل مستقل. الإلغاء يستبعد العملية من الأرقام دون حذف أثرها.",
    today: "اليوم",
    all: "الكل",
    summary: "ملخص",
    purchases: "مشتريات",
    expense: "مصروف",
    expenses: "مصروفات",
    withdrawal: "سحب",
    other: "أخرى",
    attachmentExists: "يوجد مرفق",
    noAttachment: "بدون مرفق",
    editOwnerCloseout: "تعديل التقفيلة من قبل المالك",
    newOutflow: "خرج جديد",
    transactionType: "نوع العملية",
    howMuch: "كم المبلغ؟",
    captureAttachment: "التقاط صورة المرفق",
    cameraOrGallery: "فتح الكاميرا أو اختيار صورة",
    openCamera: "الكاميرا",
    openGallery: "المعرض",
    addProof: "إثبات",
    removePhoto: "حذف الصورة",
    attachmentStoredLocally: "الصورة مضغوطة ومحفوظة محليًا لهذا البروتايب",
    captured: "تم التقاط الصورة",
    optional: "اختياري",
    note: "ملاحظة",
    notePlaceholder: "مثال: شراء خبز وخضار للمطبخ",
    save: "حفظ",
    saveSend: "حفظ الإدخال",
    dailySummary: "ملخص اليوم",
    salesChannels: "قنوات البيع",
    salesChannelsTitle: "قنوات البيع",
    paymentMethods: "طرق الدفع",
    allPaymentMethods: "كل طرق الدفع",
    dialogOk: "حسنًا",
    closeoutNotFound: "تعذر العثور على التقفيلة المرتبطة.",
    closeoutNotFoundForEntry: "تعذر العثور على التقفيلة المرتبطة بهذه العملية.",
    closeoutDeletePermanentlyTitle: "حذف التقفيلة نهائيًا؟",
    closeoutDeletePermanentlyDesc: "سيتم حذف التقفيلة وجميع عملياتها من السجل. لا يمكن التراجع عن هذا الإجراء.",
    discardCloseoutDraftOnStoreChange: "تغيير المحل سيمسح ما أدخلته في هذه التقفيلة.",
    confirmCloseoutSubmitTitle: "حفظ وإرسال التقفيلة؟",
    confirmCloseoutSubmitDesc: "سيتم إغلاق اليوم وإرسال التقفيلة — تأكد من صحة المبالغ قبل المتابعة.",
    confirmCloseoutEditTitle: "حفظ تعديلات التقفيلة؟",
    confirmCloseoutEditDesc: "سيتم تحديث التقفيلة بالمبالغ الحالية.",
    saveAndSend: "حفظ وإرسال",
    saveCloseoutChanges: "حفظ التعديلات",
    chooseCloseoutDate: "اختر تاريخ التقفيلة",
    waitForImageProcessing: "انتظر اكتمال معالجة الصور.",
    enterSalesAmount: "أدخل مبلغ الداخل",
    storeSettingsLoadingRetry: "جاري تحميل إعدادات المحل من الخادم… انتظر لحظة ثم أعد المحاولة.",
    closeoutSendFailed: "تعذر الإرسال.",
    closeoutsApiDisabled: "مسار API للتقفيلات غير مفعّل.",
    outflowSaveFailed: "تعذر حفظ الخارج على الخادم.",
    duplicateSummarySaveFailed: "تعذر حفظ الملخص المكرر على الخادم.",
    incomingChannelsSettings: "طرق الدفع",
    incomingChannels: "طرق الدفع",
    salesChannelsAndTotal: "طرق الدفع وإجمالي الداخل",
    totalSales: "إجمالي الداخل",
    salesSummaryPhoto: "صورة ملخص الداخل",
    addOutflow: "إضافة خارج",
    ownerOutflowNotice: "سجّل مصروفًا أو مشتريات دفعتها بنفسك. التحويل للعامل أو للصندوق لا يُسجل هنا.",
    operationStore: "المحل المرتبط بالعملية",
    chooseOperationStore: "اختر المحل قبل حفظ العملية",
    operationStoreHint: "سيتم تسجيل الخارج ضمن تقفيلة هذا المحل فقط.",
    category: "التصنيف",
    amount: "المبلغ",
    date: "التاريخ",
    rent: "إيجار",
    salary: "رواتب",
    utility: "كهرباء وماء",
    phone: "اتصالات",
    maintenance: "صيانة",
    rentMay: "إيجار شهر مايو",
    attachPhoto: "إرفاق صورة",
    photoAttached: "تم إرفاق الصورة",
    replacePhoto: "تغيير الصورة",
    processingPhoto: "جاري تجهيز الصورة...",
    attachmentTooLarge: "تعذر ضغط الصورة للحجم المطلوب. اختر صورة أوضح أو أصغر.",
    invalidAttachment: "المرفق يجب أن يكون صورة.",
    attachmentSaveFailed: "تعذر حفظ الصورة على الجهاز. لم يتم حفظ العملية حتى لا يظهر مرفق غير موجود.",
    discardDraftOnStoreChange: "تغيير المحل سيحذف البيانات المدخلة حاليًا. هل تريد المتابعة؟",
    saveOutflow: "حفظ",
    saveShareWhatsApp: "إرسال عبر واتساب",
    outflowSavedTitle: "تم حفظ العملية",
    outflowSavedDesc: "تم تسجيل الخارج بنجاح وسيظهر مباشرة في الرئيسية والتقارير والسجل.",
    sendOutflowQuestion: "هل تريد إرسال تفاصيل العملية عبر واتساب الآن؟",
    keepWithoutSending: "إغلاق بدون إرسال",
    shareNotebook: "معاينة الدفتر",
    notebookImagePreview: "معاينة الدفتر",
    shareViaWhatsApp: "واتساب",
    shareAttachmentWhatsApp: "إرسال الفاتورة واتساب",
    shareNotebookImage: "مشاركة الصورة",
    downloadNotebookImage: "حفظ الصورة",
    shareImageFailed: "تعذّر إنشاء صورة الدفتر. جرّب حفظ الصورة ثم أرسلها يدويًا.",
    shareImageSavedHint: "تم حفظ الصورة — أرفقها من المعرض في واتساب.",
    shareImagePasteHint: "تم فتح واتساب بالنص، والصورة منسوخة — الصق الصورة في نفس المحادثة.",
    shareImageWhatsAppPick: "اختر واتساب من قائمة المشاركة لإرسال الصورة.",
    shareImageWhatsAppUnavailable: "تم فتح واتساب بالنص، لكن تعذر نسخ الصورة تلقائيًا — أرفقها يدويًا من المعرض.",
    shareOptions: "خيارات المشاركة",
    imageFormat: "صورة الدفتر",
    pdfFormat: "PDF",
    excelFormat: "Excel",
    comingSoon: "قريبًا",
    professionalReportPreview: "معاينة التقرير الجدولي",
    exportPdf: "تصدير PDF",
    exportExcel: "تصدير Excel",
    reportFor: "تقرير",
    reportType: "نوع التقرير",
    selectedPeriod: "الفترة المحددة",
    preparedForExport: "جاهز للتصدير والمشاركة",
    account: "الحساب",
    notifications: "الإشعارات",
    dailyReminder: "تذكير ملخص اليوم",
    dailyReminderDesc: "تنبيه قبل نهاية اليوم لإرسال الداخل",
    saveNotice: "إشعار نجاح الحفظ",
    saveNoticeDesc: "تأكيد بعد إرسال أي إدخال",
    permissions: "صلاحياتك",
    permissionSummary: "إدخال ملخص اليوم",
    permissionOutflow: "إضافة مشتريات أو مصروف",
    permissionAttach: "إرفاق صورة مع الإدخال",
    ownerOnly: "التقارير وسجل العمليات الكامل يظهران للمالك فقط.",
    support: "المساعدة والدعم",
    logout: "تسجيل الخروج",
    yellow: "أصفر كلاسيكي",
    softYellow: "أصفر فاتح",
    ivory: "عاجي",
    white: "أبيض",
    greenTint: "أخضر ورقي",
    pinkTint: "وردي فاتح",
    blueTint: "أزرق فاتح",
    shopCloseout: "تقفيلة المحل",
    entered: "تم الإدخال",
    day: "اليوم",
    month: "الشهر",
    monthlySummary: "ملخص الشهر",
    dailyCloseout: "تقفيلة اليوم",
    sales: "الداخل",
    purchasesExpenses: "الخارج",
    outflowRatio: "نسبة الخارج",
    netMarginRatio: "نسبة الناتج",
    recordedMonthResult: "نتيجة الشهر المسجلة",
    netMovement: "الناتج",
    hideDetails: "إخفاء التفاصيل",
    showMore: "إظهار المزيد",
    addPaidByOwner: "إضافة خارج دفعته بنفسك",
    operations: "عمليات",
    monthlyCloseouts: "تقفيلات الشهر",
    noAttachmentsDay: "لا توجد مرفقات لهذا اليوم",
    noAttachmentsPeriod: "لا توجد مرفقات للفترة المحددة",
    attachmentGallery: "معرض المرفقات",
    selectAttachmentPeriod: "حدد فترة العرض",
    photos: "الصور",
    tracking: "المتابعة",
    period: "الفترة",
    reportNotebook: "دفتر التقارير",
    days: "الأيام",
    channels: "القنوات",
    outflow: "الخارج",
    total: "الإجمالي",
    totalOutflow: "إجمالي الخارج",
    detailedOutflowReport: "تقرير الخارج التفصيلي",
    reportDetails: "تفاصيل التقرير",
    hideReportDetails: "إخفاء التفاصيل",
    salesBreakdown: "تفصيل الداخل",
    outflowBreakdown: "تفصيل الخارج",
    detailsInOutflowTab: "لرؤية العمليات والمرفقات افتح تبويب الخارج.",
    filterByCategory: "التصنيف",
    logExpenseCategoryHint: "اختر بند المصروف لتضييق السجل",
    logFilteredSummary: "ملخص المحدد",
    logFilters: "الفلاتر",
    logResults: "النتائج",
    registerPeriodSummary: "ملخص الفترة",
    generalReportTab: "تقرير عام",
    reportGranularityDaily: "يومي",
    reportGranularityMonthly: "شهري",
    reportGranularityDaysUnit: "يوم",
    reportGranularityMonthsUnit: "شهر",
    reportSheetDaily: "تقرير الأيام",
    reportSheetMonthly: "تقرير شهري",
    chooseStoreForDayReport: "اختر محلًا لعرض تقرير الأيام.",
    noMovementPeriod: "لا حركة مالية في هذه الفترة.",
    netMarginOfSales: "من الداخل",
    logStatus: "الحالة",
    logType: "نوع العملية",
    logInPeriod: "ضمن الفترة",
    logVoidedInView: "ملغاة في العرض",
    logWithProofInView: "بمرفق في العرض",
    allCategories: "كل التصنيفات",
    thisMonth: "هذا الشهر",
    thisYear: "هذه السنة",
    customPeriod: "فترة مخصصة",
    fromDate: "من",
    toDate: "إلى",
    numberTransactions: "عدد العمليات",
    averageTransaction: "متوسط العملية",
    viewTransactions: "عرض العمليات",
    hideTransactions: "إخفاء العمليات",
    noOutflowPeriod: "لا توجد عمليات خارج مطابقة للفلاتر",
    enteredByOwner: "المالك",
    yearToDate: "2026 حتى الآن",
    noAttachmentOperations: "عمليات بدون مرفق",
    totalAttachments: "إجمالي المرفقات",
    noPhotoOperations: "عمليات بدون صورة",
    viewPhotosFromAttachments: "عرض الصور من قسم المرفقات",
    operationalOnly: "تقارير متابعة تشغيلية وليست تقارير محاسبية",
    time: "الوقت",
    enteredBy: "بواسطة",
    openAttachment: "فتح صورة المرفق",
    savedNotice: "تم الحفظ وسيظهر الإدخال لدى المالك",
    tagline: "دفتر تقفيلتك في جوالك",
    valueDesc: "إدخال بسيط للموظف، وملخص واضح للمالك، ومرفقات مرتبطة بكل عملية دون تعقيد محاسبي.",
    cash: "نقد",
    bank: "بنك",
    card: "بطاقة",
    online: "أونلاين",
    mada: "مدى",
    apple: "Apple Pay",
    jahez: "جاهز",
    hunger: "هنقرستيشن",
    keeta: "كيتا",
    breadVegetables: "شراء خبز وخضار للمطبخ",
    cleaning: "مواد تنظيف",
    dailyNeed: "احتياج يومي للمطبخ",
    salesSummary: "صورة ملخص الداخل",
    yesterdaySummary: "ملخص أمس",
    dailyPurchases: "مشتريات يومية",
    operatingExpense: "مصروف تشغيل",
    shortBread: "شراء خبز وخضار",
    businessSettings: "الإعدادات",
    storeSettings: "إعدادات المحل",
    storeConfiguration: "إعدادات التشغيل",
    storeSpecificSettings: "هذه الإعدادات تخص هذا المحل فقط ولا تؤثر على المحلات الأخرى.",
    backToSettings: "العودة للإعدادات",
    linkedEmployees: "الموظفون المرتبطون بالمحل",
    noLinkedEmployees: "لا يوجد موظفون مرتبطون بهذا المحل.",
    generalPreferences: "التفضيلات العامة",
    businessProfile: "بيانات المحل",
    ownerAccount: "حساب المالك",
    ownerName: "محمد الهاجري",
    myAccountSecurity: "حسابي والأمان",
    ownerFullName: "اسم المالك",
    editOwnerName: "تعديل اسم المالك",
    ownerRenameProfileHint: "تغيير الاسم يطبق على الحساب والإدخالات الجديدة فقط. يحتفظ السجل السابق باسم منفذ العملية وقت تسجيلها.",
    ownerAccountEmail: "البريد الإلكتروني",
    ownerAccountPhone: "رقم الجوال",
    ownerAccountContactTitle: "بيانات التواصل",
    ownerAccountContactHint: "البريد يُستخدم لاستعادة كلمة المرور. الدخول اليومي يتم برقم الجوال.",
    ownerAccountLoginTitle: "تسجيل الدخول",
    ownerAccountLoginHint: "استخدم رقم الجوال وكلمة المرور التي أنشأتها عند إعداد الحساب.",
    ownerAccountChangePassword: "تغيير كلمة المرور",
    ownerAccountCurrentPassword: "كلمة المرور الحالية",
    ownerAccountNewPassword: "كلمة المرور الجديدة",
    ownerAccountConfirmPassword: "تأكيد كلمة المرور",
    ownerAccountPasswordChanged: "تم تحديث كلمة المرور.",
    ownerAccountPlanTitle: "الباقة والاشتراك",
    ownerAccountPlanUpgradeHint: "لترقية الباقة أو الانتقال من التجريبي إلى المدفوع، أرسل طلبًا لفريق الدعم عبر واتساب.",
    ownerAccountRequestUpgrade: "طلب ترقية الباقة",
    ownerAccountLoading: "جاري تحميل بيانات الحساب…",
    ownerAccountLoadError: "تعذر تحميل بيانات الحساب.",
    ownerAccountNotAvailable: "غير متوفر",
    loginMethod: "طريقة تسجيل الدخول",
    currentLoginMethod: "الطريقة الحالية",
    mobileOtpLogin: "رقم الجوال + رمز تحقق",
    usernamePasswordLogin: "اسم مستخدم وكلمة مرور",
    availableLater: "متاح لاحقًا",
    futureLoginMethodHint: "سيتم تفعيل اسم المستخدم وكلمة المرور لاحقًا بعد بناء نظام المصادقة الآمن، دون التأثير على بيانات المنشأة أو الصلاحيات.",
    futureLoginOnLoginScreen: "تجريبي الآن: owner / demo123. طرق الواتساب/الإيميل جاهزة برمجيًا وتُفعّل لاحقًا.",
    loginWithPhone: "جوال + رمز",
    loginWithPassword: "مستخدم وكلمة مرور",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    employeeLogin: "دخول الموظف",
    employeeLoginSubtitle: "اختر اسمك وأدخل الرمز",
    employeePin: "رمز الدخول",
    employeePinHint: "تجريبي: 1234 لكل الموظفين",
    backToOwnerLogin: "العودة لدخول المالك",
    invalidOtp: "أدخل الرمز 1234 في البروتايب",
    invalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
    invalidEmployeePin: "رمز الدخول غير صحيح",
    closeoutInAppAlert: "وصلت تقفيلة يوم جديدة",
    closeoutInAppHint: "سجّلها من الموظف — افتح السجل",
    openCloseoutInRegister: "عرض في السجل",
    dismissAlert: "تجاهل",
    dailyCloseoutAlertPrototype: "تنبيه داخل التطبيق للمالك عند إرسال الموظف للتقفيلة",
    helpCenterTitle: "مركز المساعدة",
    prototypeBuildLabel: "نسخة النموذج",
    helpCenterBody: "البروتايب يغطي: تقفيلة يومية، خارج، سجل، تقارير، ومشاركة الدفتر. للدعم استخدم واتساب من الإعدادات.",
    prototypeDemoAccess: "تجريبي في البروتايب",
    saveAccountSettings: "حفظ بيانات الحساب",
    shopName: "اسم المحل",
    renameStoreHint: "تغيير الاسم لا يؤثر على العمليات أو التقارير السابقة؛ جميع البيانات تبقى مرتبطة بنفس المحل.",
    closeoutSetup: "إعداد التقفيلة",
    setupStore: "المحل المراد ضبطه",
    storeSalesChannelScope: "طرق الدفع تضبط لكل محل بشكل مستقل ولا تؤثر على المحلات الأخرى.",
    visibleSalesChannels: "طرق الدفع الظاهرة للموظف",
    manage: "تعديل",
    outflowCategories: "بنود المصروف",
    notebookAppearance: "شكل الدفتر",
    notebookAppearanceDesc: "لون دفتر التقفيلة والتقارير",
    autoSavedAccount: "يُحفظ تلقائيًا ويُطبق على الدفتر والتقارير والمشاركة.",
    configure: "إدارة",
    close: "إغلاق",
    addPaymentMethod: "إضافة طريقة دفع",
    addSalesChannel: "إضافة قناة بيع",
    addIncomeSource: "إضافة بند مخصص",
    customPaymentMethodName: "اسم طريقة دفع مخصصة",
    customSalesChannelName: "اسم قناة بيع مخصصة",
    customIncomeSourceName: "اسم بند مخصص",
    channelControlHint: "طريقة الدفع الموقوفة تختفي من الإدخالات الجديدة وتبقى في التقارير السابقة.",
    stopChannel: "إيقاف",
    restoreChannel: "إعادة تفعيل",
    noSalesChannels: "لا توجد طرق دفع مفعّلة. أضف أو فعّل طريقة دفع أولًا.",
    addCategory: "إضافة تصنيف",
    activeItemsHint: "اضغط على العنصر لإظهاره أو إخفائه من الإدخال.",
    teamMember: "عضو الفريق",
    addEmployee: "إضافة موظف",
    employeeMobile: "رقم جوال الموظف",
    employeeMobileMissing: "لم يُضبط جوال دخول بعد",
    allowEntries: "السماح بالإدخالات",
    billingDetails: "تفاصيل الاشتراك",
    renewalDate: "موعد التجديد القادم",
    paymentMethod: "طريقة الدفع",
    contactSupport: "التواصل مع الدعم",
    whatsappSupport: "واتساب الدعم",
    helpCenter: "مركز المساعدة",
    activeChannels: "القنوات النشطة",
    activeCategories: "التصنيفات النشطة",
    changesSaved: "تم حفظ التعديلات",
    saveSettings: "حفظ التعديلات",
    cancelChanges: "إلغاء التعديلات",
    saveToApplyTheme: "اختر الشكل ثم اضغط حفظ لتطبيقه على الدفتر والتقارير والمشاركة.",
    newEmployeeName: "اسم الموظف",
    ownerNotifications: "تنبيهات المالك",
    dailyCloseoutAlert: "تنبيه وصول تقفيلة اليوم",
    dailyCloseoutAlertDesc: "إشعار عند إرسال الموظف لملخص اليوم",
    teamAccess: "الموظفون والمحلات المرتبطة",
    linkedStores: "المحلات المرتبطة",
    assignStores: "حدد المحل أو المحلات التي يستطيع الموظف الإدخال عليها",
    selectAtLeastOneStore: "يجب اختيار محل واحد على الأقل للموظف.",
    currentWorkStore: "المحل الحالي للإدخال",
    switchWorkStore: "تغيير المحل",
    noAssignedStores: "لا يوجد محل مرتبط بهذا الموظف. راجع المالك.",
    employeeEntryOnly: "صلاحية الموظف ثابتة: إدخال فقط للمحلات المرتبطة به.",
    employeeCount: "موظف واحد لديه صلاحية الإدخال",
    manageEmployees: "إدارة الموظفين",
    subscription: "الاشتراك",
    subscriptionDetails: "الخطة والاشتراك",
    subscriptionLoading: "جاري التحميل...",
    currentPlan: "الخطة الحالية",
    monthlyPrice: "السعر الشهري",
    planFeatures: "مميزات الخطة",
    upgradeOptions: "خيارات الترقية",
    requestUpgrade: "طلب ترقية",
    upgradeSupportHint: "الترقية تتم عبر فريق الدعم حاليًا. اضغط «طلب ترقية» لفتح واتساب برسالة جاهزة.",
    topPlanHint: "أنت على أعلى خطة متاحة حاليًا. تواصل مع الدعم لأي تعديلات إضافية.",
    retryLoad: "إعادة المحاولة",
    trialPlanBadge: "تجريبي",
    trialPlanTitle: "خطة تجريبية مجانية",
    trialPlanDescription: "15 يومًا — حتى 3 محلات و3 مستخدمين. بعد انتهاء التجربة يجب الترقية لخطة مدفوعة للاستمرار.",
    trialDaysRemaining: "الأيام المتبقية",
    trialEndsOn: "تنتهي التجربة في",
    upgradeToPaid: "الترقية إلى مدفوعة",
    billingCycleLabel: "دورة الاشتراك",
    renewalDaysRemaining: "الأيام المتبقية للاشتراك",
    subscriptionExpiredTitle: "انتهى الاشتراك",
    subscriptionExpiredBody: "انتهت فترة الاشتراك. جدّد الآن لمواصلة إضافة المحلات والموظفين.",
    subscriptionTrialExpiredBody: "انتهت التجربة المجانية. فعّل خطة مدفوعة للاستمرار.",
    subscriptionGraceTitle: "فترة سماح للتجديد",
    subscriptionGraceBody: "انتهى الاشتراك. يتبقى {days} أيام سماح قبل إيقاف الإضافات.",
    subscriptionRenewalSoon14: "تذكير: الاشتراك ينتهي خلال أسبوعين",
    subscriptionRenewalSoon7: "تذكير: الاشتراك ينتهي خلال أسبوع",
    subscriptionRenewalSoon3: "تذكير عاجل: الاشتراك ينتهي قريبًا",
    subscriptionRenewalSoonBody: "يتبقى {days} يوم — التجديد بتاريخ {date}.",
    openSubscriptionDetails: "تفاصيل الاشتراك",
    renewViaWhatsApp: "تجديد عبر واتساب",
    allStores: "الكل",
    selectStore: "اختر المحل",
    searchStore: "ابحث عن محل أو فرع",
    viewStores: "عرض المحلات",
    hideStores: "إخفاء المحلات",
    storeResults: "نتائج المحلات",
    noActiveStores: "لا توجد محلات نشطة",
    combinedCloseout: "كل المحلات",
    activeStoresScope: "جميع المحلات النشطة",
    combinedReport: "كل المحلات",
    store: "المحل",
    result: "الناتج",
    status: "الحالة",
    completed: "مكتملة",
    chooseStoreForDetails: "اختر محلًا لعرض المرفقات والتفاصيل وإضافة الخارج",
    shamiShort: "الشامي",
    arzShort: "ARZ",
    shamiLocation: "الظهران - الدوحة",
    arzLocation: "الخبر - العليا",
    combinedTotal: "الإجمالي",
    loginTitle: "ادخل إلى تقفيلة",
    loginSubtitle: "تابع تقفيلة محلك من جوالك ببساطة",
    loginGatewayTitle: "مرحبًا في تقفيلة",
    loginGatewaySubtitle: "اختر دخول المالك أو الموظف للمتابعة",
    loginGatewayOwnerHint: "تقارير، سجل، إعدادات المحل",
    loginGatewayEmployeeHint: "تقفيل يومي وإدخال العمليات",
    backToLoginGateway: "العودة لاختيار الدخول",
    switchToEmployeeLogin: "دخول كموظف",
    switchToOwnerLogin: "دخول كمالك",
    switchPortalConfirmEmployee: "سينتهي دخولك الحالي وستنتقل إلى شاشة دخول الموظف.",
    switchPortalConfirmOwner: "سينتهي دخولك الحالي وستنتقل إلى شاشة دخول المالك.",
    mobileNumber: "رقم الجوال",
    mobileHint: "سيصلك رمز تحقق على رقم الجوال — يمكنك إدخال 05 أو 5",
    sendCode: "إرسال رمز التحقق",
    verificationCode: "رمز التحقق",
    codeSentTo: "تم إرسال رمز التحقق إلى",
    verifyContinue: "تحقق وادخل",
    changeNumber: "تغيير الرقم",
    phoneLoginOnly: "طريقة الدخول الحالية: رقم الجوال ورمز تحقق آمن",
    linkedAccountNote: "سيتم فتح الحساب والصلاحيات المرتبطة برقمك تلقائيًا",
    myStores: "محلاتي",
    activeStores: "المحلات النشطة",
    archivedStoresList: "المؤرشفة",
    showArchived: "عرض المؤرشفة",
    hideArchived: "إخفاء المؤرشفة",
    noArchivedStores: "لا توجد محلات مؤرشفة",
    addStore: "إضافة محل",
    archiveStore: "أرشفة",
    archivedStore: "مؤرشف",
    storeActive: "نشط",
    addNewStore: "إضافة محل جديد",
    newStoreName: "اسم المحل الجديد",
    newStoreLocation: "الموقع أو الفرع",
    archiveNotice: "الأرشفة توقف الإدخالات الجديدة وتحتفظ بالتقفيلات والمرفقات السابقة.",
    confirmAddStore: "حفظ المحل",
    delete: "حذف",
    deleteStore: "حذف المحل",
    deleteChannel: "إخفاء طريقة الدفع",
    deleteUser: "حذف المستخدم",
    confirmSafeDelete: "تأكيد الإجراء",
    cancel: "إلغاء",
    storeDeleteWithDataTitle: "لا يمكن حذف محل لديه بيانات",
    storeDeleteWithDataDesc: "يحتوي هذا المحل على تقفيلات أو سجلات سابقة. سيتم أرشفته وإيقاف الإدخالات الجديدة فقط، وستبقى التقارير والمرفقات محفوظة.",
    storeDeleteEmptyTitle: "حذف المحل الفارغ؟",
    storeDeleteEmptyDesc: "هذا المحل لا يحتوي على بيانات مسجلة. سيتم حذفه من القائمة نهائيًا.",
    userDeleteTitle: "إزالة صلاحية المستخدم؟",
    userDeleteDesc: "سيتم إيقاف دخول المستخدم وإزالته من الفريق النشط. ستبقى الإدخالات السابقة باسمه ضمن السجل.",
    channelDeleteTitle: "إيقاف طريقة الدفع؟",
    channelDeleteDesc: "ستختفي طريقة الدفع من الإدخالات الجديدة، لكنها ستبقى محفوظة في التقارير السابقة ولا تتأثر الأرقام التاريخية.",
    archiveAndKeepData: "أرشفة وحفظ البيانات",
    deleteEmptyStore: "حذف المحل الفارغ",
    revokeAccess: "إزالة الصلاحية",
    retireChannel: "إيقاف القناة",
    safeDeleteNotice: "الحذف الآمن يحافظ على التقارير والسجلات السابقة.",
    selectDay: "اختر اليوم",
    noEntriesDay: "لا توجد إدخالات في هذا اليوم",
    selectMonth: "اختر الشهر",
    selectYear: "اختر السنة",
    selectRange: "اختر الفترة",
    year: "السنة",
    custom: "مخصص",
    applyPeriod: "تطبيق الفترة",
    applyFilters: "تطبيق",
    resetFilters: "إعادة تعيين",
    year2026: "2026",
    year2025: "2025",
    may2026: "مايو 2026",
    april2026: "أبريل 2026",
    march2026: "مارس 2026",
    previousMonth: "الشهر السابق",
    nextMonth: "الشهر التالي",
    suggestedNextCloseout: "اليوم المقترح بناءً على آخر تقفيلة محفوظة",
    changeDateAnytime: "يمكنك تغيير التاريخ عند إدخال عملية متأخرة أو تصحيح سابق.",
    archivedReadOnly: "مؤرشف — عرض فقط",
    viewPastReports: "عرض التقارير السابقة",
    viewPastAttachments: "عرض السجل السابق",
    atLeastOneCategory: "يجب إبقاء تصنيف واحد على الأقل للإدخالات الجديدة.",
    noActiveEmployee: "لا يوجد موظف نشط حاليًا. فعّل موظفًا من إعدادات المالك.",
    noCloseoutsPeriod: "لا توجد تقفيلات مسجلة لهذه الفترة.",
    noSalesChannelsPeriod: "لا توجد طرق دفع مسجلة لهذه الفترة.",
    noPaymentMethodsPeriod: "لا توجد طرق دفع",
    voided: "ملغاة",
    voidEntry: "إلغاء العملية",
    voidDialogTitle: "إلغاء هذه العملية؟",
    voidConfirm: "سيتم استبعاد العملية من الأرقام والتقارير، مع الاحتفاظ بها في السجل والمرفقات للرجوع إليها.",
    voidReasonPrompt: "سبب الإلغاء - اختياري",
    confirmVoid: "تأكيد الإلغاء",
    voidedByOwner: "ألغيت بواسطة المالك",
    voidReason: "سبب الإلغاء",
    duplicateSalesTitle: "يوجد ملخص داخل سابق",
    duplicateSalesWarning: "تم تسجيل ملخص داخل نشط لهذا المحل في نفس اليوم. إذا تابعت، سيضاف هذا الإدخال إلى الإجمالي كسجل مستقل ولن يستبدل الإدخال السابق.",
    previousSalesEntries: "ملخصات الداخل الحالية",
    saveAdditionalEntry: "حفظ كإدخال إضافي",
    duplicateSalesOwnerAlert: "يوجد أكثر من ملخص داخل مسجل لنفس اليوم",
    duplicateSalesOwnerHint: "راجع السجل للتأكد من أن الإدخالات صحيحة وليست مكررة.",
    openInLog: "فتح السجل",
    approveMultipleSales: "اعتماد الإدخالات",
    approveMultipleSalesHint: "اعتماد أن ملخصات الداخل المتعددة صحيحة وإيقاف التنبيه لهذه النسخة.",
    restoreEntry: "استعادة العملية",
    restoreDialogTitle: "استعادة هذه العملية؟",
    restoreConfirm: "ستعود العملية إلى الأرقام والتقارير مع الاحتفاظ بسجل الإلغاء والاستعادة.",
    restoreReasonPrompt: "سبب الاستعادة - اختياري",
    confirmRestore: "تأكيد الاستعادة",
    restored: "مستعادة",
    restoredByOwner: "استعيدت بواسطة المالك",
    restoreReason: "سبب الاستعادة",
    saving: "جاري الحفظ...",
    enterOwnerSummary: "إدخال تقفيلة اليوم",
    atLeastOneChannel: "يجب إبقاء طريقة دفع أو قناة بيع واحدة على الأقل لإدخال الداخل.",
    stoppedChannels: "القنوات الموقوفة",
    noStoppedChannels: "لا توجد قنوات موقوفة.",
    invalidDateRange: "تاريخ البداية يجب أن يكون قبل تاريخ النهاية.",
    archiveStoreTitle: "أرشفة المحل؟",
    archiveStoreDesc: "سيتم إيقاف الإدخالات الجديدة مع الاحتفاظ بجميع التقارير والسجلات والمرفقات السابقة.",
    confirmArchive: "تأكيد الأرشفة",
    chooseStoreForSummary: "اختر المحل قبل تسجيل التقفيلة",
    chooseStoreToStartEntry: "اختر المحل لتفعيل خانات الإدخال",
    futureDateNotAllowed: "لا يمكن تسجيل عملية بتاريخ مستقبلي.",
    closeoutRequiredForEntry: "لا يمكن حفظ داخل أو خارج بدون تقفيلة. افتح «تقفيلاتي» أو اختر تقفيلة أولًا.",
    auditTrail: "سجل الحركة",
    actionCreated: "تم الإنشاء",
    actionVoided: "تم الإلغاء",
    actionRestored: "تمت الاستعادة",
    actionReviewed: "تمت مراجعة المرفق",
    actionDuplicateApproved: "تم اعتماد تعدد الإدخالات",
    channelsReport: "تقرير القنوات",
    daysReport: "تقرير الأيام",
    attachmentsReport: "تقرير المرفقات",
    shopsComparisonReport: "مقارنة المحلات",
    salesShort: "الداخل",
    outflowShort: "الخارج",
    archiveStaffWarning: "تنبيه: سيصبح الموظفون التاليون بدون محل نشط للإدخال بعد الأرشفة:",
    saveTeamChanges: "حفظ صلاحيات الفريق",
    desktopHeroTitle: "دفتر تقفيلتك اليومية في جوالك",
    desktopHeroDesc: "سجّل الداخل والخارج والمرفقات، وتابع حركة محلاتك يوميًا بوضوح، بدون تعقيد الأنظمة المحاسبية.",
    ownerLogin: "تسجيل دخول المالك",
    openOnMobile: "افتح التطبيق من جوالك",
    qrPrototypeNote: "رمز تجريبي — يتم ربطه عند نشر النسخة الفعلية",
    fastEntryTitle: "إدخال سريع",
    fastEntryDesc: "الموظف يسجل داخل اليوم والخارج خلال دقائق.",
    clearFollowupTitle: "متابعة واضحة",
    clearFollowupDesc: "المالك يراجع الحركة والسجل لكل محل من مكان واحد.",
    proofLinkedTitle: "إثباتات مرتبطة",
    proofLinkedDesc: "أرفق صورة مع العملية عند الحاجة وراجعها لاحقًا.",
    targetBusinessTitle: "مصمم للمحلات التي تحتاج تقفيلة يومية بسيطة",
    targetBusinessDesc: "للمطاعم والكافيهات والمحلات الصغيرة واللاونجات التي تريد متابعة يومية واضحة بدون تحويل العمل إلى نظام محاسبي كامل.",
    mobileFirstBadge: "مصمم للجوال أولًا",
    desktopOwnerLater: "لوحة المالك على الكمبيوتر ضمن التطوير اللاحق",
    closeLogin: "إغلاق الدخول",
    desktopDemoStore: "مطعم النجاح",
    desktopDemoLocation: "الفرع الرئيسي",
  },
  en: {
    appName: "Taqfeelah",
    restaurant: "Al Moallem Al Shami Grill",
    employee: "Employee",
    staffBadge: "Staff",
    owner: "Owner",
    home: "Home",
    entries: "Entries",
    settings: "Settings",
    reports: "Reports",
    attachments: "Attachments",
    active: "Active",
    openEntry: "Open for entries",
    todayEntries: "Today's entries",
    enterDailySummary: "Enter daily summary",
    addPurchaseExpense: "Add purchase / expense",
    amountNoteOptionalPhoto: "Amount + note + optional photo",
    recentEntries: "Recent entries",
    viewAll: "View all",
    register: "Log",
    ownerNotebook: "My notebook",
    ownerNotebookAdd: "Add to notebook",
    ownerNotebookTask: "Task",
    ownerNotebookNote: "Note",
    ownerNotebookEmpty: "No notes yet. Start your private notebook.",
    ownerNotebookPlaceholder: "Write a note or task…",
    ownerNotebookHint: "Your private notes — employees cannot see them.",
    ownerNotebookActive: "Active",
    ownerNotebookAll: "All",
    ownerNotebookTasks: "Tasks",
    ownerNotebookNotes: "Notes",
    ownerNotebookDone: "Done",
    ownerNotebookNew: "New entry",
    ownerNotebookPrivate: "Private · owner only",
    ownerNotebookItems: "items",
    ownerNotebookEmptyCta: "Tap «New entry» to add your first note or task.",
    ownerNotebookSharePreview: "Notebook note preview",
    ownerNotebookShare: "Share",
    ownerNotebookTaskTitle: "Task title (optional)",
    ownerNotebookAddItem: "Add item",
    ownerNotebookItemPlaceholder: "Write an item…",
    loading: "Loading…",
    operationsLog: "Operations log",
    myEntries: "My entries",
    activeEntries: "Active",
    withAttachment: "With attachment only",
    allTypes: "All types",
    noOperationsMatch: "No operations match the selected filters.",
    logPurpose: "Each entry is stored as an independent record. Voiding excludes it from totals without erasing its trace.",
    today: "Today",
    all: "All",
    summary: "Summary",
    purchases: "Purchases",
    expense: "Expense",
    expenses: "Expenses",
    withdrawal: "Withdrawal",
    other: "Other",
    attachmentExists: "Attachment added",
    noAttachment: "No attachment",
    editOwnerCloseout: "Edit closeout (owner)",
    newOutflow: "New outflow",
    transactionType: "Transaction type",
    howMuch: "Amount",
    captureAttachment: "Capture attachment photo",
    cameraOrGallery: "Open camera or choose image",
    openCamera: "Camera",
    openGallery: "Gallery",
    addProof: "Proof",
    removePhoto: "Remove photo",
    attachmentStoredLocally: "Compressed image saved locally for this prototype",
    captured: "Photo captured",
    optional: "Optional",
    note: "Note",
    notePlaceholder: "Example: kitchen bread and vegetables",
    save: "Save",
    saveSend: "Save entry",
    dailySummary: "Daily summary",
    salesChannels: "Sales channels",
    salesChannelsTitle: "Sales channels",
    paymentMethods: "Payment methods",
    allPaymentMethods: "All payment methods",
    dialogOk: "OK",
    closeoutNotFound: "Could not find the linked closeout.",
    closeoutNotFoundForEntry: "Could not find the closeout linked to this entry.",
    closeoutDeletePermanentlyTitle: "Delete this closeout permanently?",
    closeoutDeletePermanentlyDesc: "The closeout and all of its entries will be removed from the log. This cannot be undone.",
    discardCloseoutDraftOnStoreChange: "Changing the shop will clear what you entered in this closeout.",
    confirmCloseoutSubmitTitle: "Save and send this closeout?",
    confirmCloseoutSubmitDesc: "The day will be closed and the closeout sent — check the amounts before continuing.",
    confirmCloseoutEditTitle: "Save closeout changes?",
    confirmCloseoutEditDesc: "The closeout will be updated with the current amounts.",
    saveAndSend: "Save & send",
    saveCloseoutChanges: "Save changes",
    chooseCloseoutDate: "Pick a closeout date",
    waitForImageProcessing: "Wait for images to finish processing.",
    enterSalesAmount: "Enter sales amount",
    storeSettingsLoadingRetry: "Store settings are still loading from the server… wait a moment and try again.",
    closeoutSendFailed: "Failed to send.",
    closeoutsApiDisabled: "Closeouts API is disabled.",
    outflowSaveFailed: "Failed to save outflow on server.",
    duplicateSummarySaveFailed: "Failed to save duplicate summary on server.",
    incomingChannelsSettings: "Payment methods",
    incomingChannels: "Payment methods",
    salesChannelsAndTotal: "Payment methods and total incoming",
    totalSales: "Total sales",
    salesSummaryPhoto: "Sales summary photo",
    addOutflow: "Add outflow",
    ownerOutflowNotice: "Record expenses or purchases you paid directly. Transfers to an employee or cash drawer are not recorded here.",
    operationStore: "Shop for this transaction",
    chooseOperationStore: "Select a shop before saving this transaction",
    operationStoreHint: "This outflow will be recorded only in the selected shop closeout.",
    category: "Category",
    amount: "Amount",
    date: "Date",
    rent: "Rent",
    salary: "Salaries",
    utility: "Electricity & water",
    phone: "Telecom",
    maintenance: "Maintenance",
    rentMay: "May rent payment",
    attachPhoto: "Attach photo",
    photoAttached: "Photo attached",
    replacePhoto: "Replace photo",
    processingPhoto: "Preparing photo...",
    attachmentTooLarge: "The image could not be compressed to the allowed size. Select a clearer or smaller image.",
    invalidAttachment: "The attachment must be an image.",
    attachmentSaveFailed: "The image could not be saved on this device. The entry was not saved to avoid a missing attachment.",
    discardDraftOnStoreChange: "Changing the shop will clear the current unsaved entry. Continue?",
    saveOutflow: "Save",
    saveShareWhatsApp: "Send via WhatsApp",
    outflowSavedTitle: "Transaction saved",
    outflowSavedDesc: "The outflow was recorded successfully and now appears in the home view, reports, and log.",
    sendOutflowQuestion: "Would you like to send the transaction details through WhatsApp now?",
    keepWithoutSending: "Close without sending",
    shareNotebook: "Preview notebook",
    notebookImagePreview: "Notebook preview",
    shareViaWhatsApp: "WhatsApp",
    shareAttachmentWhatsApp: "Send invoice on WhatsApp",
    shareNotebookImage: "Share image",
    downloadNotebookImage: "Save image",
    shareImageFailed: "Could not create the notebook image. Try saving it and sending manually.",
    shareImageSavedHint: "Image saved â€” attach it from your gallery in WhatsApp.",
    shareImagePasteHint: "WhatsApp opened with text, and the image was copied â€” paste it in the same chat.",
    shareImageWhatsAppPick: "Choose WhatsApp from the share menu to send the image.",
    shareImageWhatsAppUnavailable: "WhatsApp opened with text, but image copy is unavailable â€” attach it manually from gallery.",
    shareOptions: "Share options",
    imageFormat: "Notebook image",
    pdfFormat: "PDF",
    excelFormat: "Excel",
    comingSoon: "Coming soon",
    professionalReportPreview: "Tabular report preview",
    exportPdf: "Export PDF",
    exportExcel: "Export Excel",
    reportFor: "Report",
    reportType: "Report type",
    selectedPeriod: "Selected period",
    preparedForExport: "Ready to export and share",
    account: "Account",
    notifications: "Notifications",
    dailyReminder: "Daily summary reminder",
    dailyReminderDesc: "Reminder before end of day to submit sales",
    saveNotice: "Save confirmation",
    saveNoticeDesc: "Confirmation after submitting an entry",
    permissions: "Your permissions",
    permissionSummary: "Enter daily summary",
    permissionOutflow: "Add purchase or expense",
    permissionAttach: "Attach a photo to an entry",
    ownerOnly: "Full reports and the operations log are only available to the owner.",
    support: "Help and support",
    logout: "Log out",
    yellow: "Classic yellow",
    softYellow: "Light yellow",
    ivory: "Ivory",
    white: "White",
    greenTint: "Green tint",
    pinkTint: "Light pink",
    blueTint: "Light blue",
    shopCloseout: "Shop closeout",
    entered: "Submitted",
    day: "Day",
    month: "Month",
    monthlySummary: "Monthly summary",
    dailyCloseout: "Daily closeout",
    sales: "Sales",
    purchasesExpenses: "Outflow",
    outflowRatio: "Outflow ratio",
    netMarginRatio: "Net margin ratio",
    recordedMonthResult: "Recorded month result",
    netMovement: "Net",
    hideDetails: "Hide details",
    showMore: "Show more",
    addPaidByOwner: "Add outflow you paid",
    operations: "Operations",
    monthlyCloseouts: "Monthly closeouts",
    noAttachmentsDay: "No attachments for this day",
    noAttachmentsPeriod: "No attachments for the selected period",
    attachmentGallery: "Attachment gallery",
    selectAttachmentPeriod: "Select viewing period",
    photos: "Photos",
    tracking: "Tracking",
    period: "Period",
    reportNotebook: "Reports notebook",
    days: "Days",
    channels: "Channels",
    outflow: "Outflow",
    total: "Total",
    totalOutflow: "Total outflow",
    detailedOutflowReport: "Detailed outflow report",
    reportDetails: "Report details",
    hideReportDetails: "Hide details",
    salesBreakdown: "Sales breakdown",
    outflowBreakdown: "Outflow breakdown",
    detailsInOutflowTab: "Open the Outflow tab to view transactions and attachments.",
    filterByCategory: "Category",
    logExpenseCategoryHint: "Pick an expense category to narrow the log",
    logFilteredSummary: "Filtered summary",
    logFilters: "Filters",
    logResults: "Results",
    registerPeriodSummary: "Period summary",
    generalReportTab: "General report",
    reportGranularityDaily: "Daily",
    reportGranularityMonthly: "Monthly",
    reportGranularityDaysUnit: "days",
    reportGranularityMonthsUnit: "months",
    reportSheetDaily: "Daily report",
    reportSheetMonthly: "Monthly report",
    chooseStoreForDayReport: "Select a shop to view the days report.",
    noMovementPeriod: "No financial activity in this period.",
    netMarginOfSales: "of sales",
    logStatus: "Status",
    logType: "Operation type",
    logInPeriod: "In period",
    logVoidedInView: "Voided in view",
    logWithProofInView: "With attachment in view",
    allCategories: "All categories",
    thisMonth: "This month",
    thisYear: "This year",
    customPeriod: "Custom period",
    fromDate: "From",
    toDate: "To",
    numberTransactions: "Transactions",
    averageTransaction: "Average transaction",
    viewTransactions: "View transactions",
    hideTransactions: "Hide transactions",
    noOutflowPeriod: "No outflow transactions match these filters",
    enteredByOwner: "Owner",
    yearToDate: "2026 year to date",
    noAttachmentOperations: "Operations without attachment",
    totalAttachments: "Total attachments",
    noPhotoOperations: "Operations without photo",
    viewPhotosFromAttachments: "View photos in Attachments",
    operationalOnly: "Operational tracking reports only, not accounting reports",
    time: "Time",
    enteredBy: "By",
    openAttachment: "Open attachment photo",
    savedNotice: "Saved. The entry will appear for the owner.",
    tagline: "Your closeout notebook on your phone",
    valueDesc: "Simple entries for employees, a clear summary for owners, and attachments tied to each operation without accounting complexity.",
    cash: "Cash",
    bank: "Bank",
    card: "Card",
    online: "Online",
    mada: "Mada",
    apple: "Apple Pay",
    jahez: "Jahez",
    hunger: "HungerStation",
    keeta: "Keeta",
    breadVegetables: "Kitchen bread and vegetables",
    cleaning: "Cleaning supplies",
    dailyNeed: "Daily kitchen needs",
    salesSummary: "Sales summary photo",
    yesterdaySummary: "Yesterday's summary",
    dailyPurchases: "Daily purchases",
    operatingExpense: "Operating expense",
    shortBread: "Bread and vegetables",
    businessSettings: "Settings",
    storeSettings: "Shop settings",
    storeConfiguration: "Operations settings",
    storeSpecificSettings: "These settings apply only to this shop and do not affect other shops.",
    backToSettings: "Back to settings",
    linkedEmployees: "Staff assigned to this shop",
    noLinkedEmployees: "No staff are assigned to this shop.",
    generalPreferences: "General preferences",
    businessProfile: "Business profile",
    ownerAccount: "Owner account",
    ownerName: "Mohammad Alhajri",
    myAccountSecurity: "My account & security",
    ownerFullName: "Owner name",
    editOwnerName: "Edit owner name",
    ownerRenameProfileHint: "Changing the name applies to the account and new entries only. Previous records retain the actor name captured at the time of entry.",
    ownerAccountEmail: "Email address",
    ownerAccountPhone: "Mobile number",
    ownerAccountContactTitle: "Contact details",
    ownerAccountContactHint: "Email is used for password recovery. Daily sign-in uses your mobile number.",
    ownerAccountLoginTitle: "Sign-in",
    ownerAccountLoginHint: "Use the mobile number and password you set during account setup.",
    ownerAccountChangePassword: "Change password",
    ownerAccountCurrentPassword: "Current password",
    ownerAccountNewPassword: "New password",
    ownerAccountConfirmPassword: "Confirm password",
    ownerAccountPasswordChanged: "Password updated.",
    ownerAccountPlanTitle: "Plan & subscription",
    ownerAccountPlanUpgradeHint: "To upgrade your plan or move from trial to paid, send a request to support via WhatsApp.",
    ownerAccountRequestUpgrade: "Request plan upgrade",
    ownerAccountLoading: "Loading account details…",
    ownerAccountLoadError: "Failed to load account details.",
    ownerAccountNotAvailable: "Not available",
    loginMethod: "Sign-in method",
    currentLoginMethod: "Current method",
    mobileOtpLogin: "Mobile number + verification code",
    usernamePasswordLogin: "Username and password",
    availableLater: "Available later",
    futureLoginMethodHint: "Username and password sign-in will be enabled later after secure authentication is built, without affecting organization data or access rules.",
    futureLoginOnLoginScreen: "Demo now: owner / demo123. WhatsApp/email methods are code-ready and can be enabled later.",
    loginWithPhone: "Mobile + code",
    loginWithPassword: "Username & password",
    username: "Username",
    password: "Password",
    employeeLogin: "Employee sign-in",
    employeeLoginSubtitle: "Pick your name and enter your PIN",
    employeePin: "Sign-in PIN",
    employeePinHint: "Demo: 1234 for all staff",
    backToOwnerLogin: "Back to owner sign-in",
    invalidOtp: "Enter code 1234 in this prototype",
    invalidCredentials: "Incorrect username or password",
    invalidEmployeePin: "Incorrect PIN",
    closeoutInAppAlert: "New daily closeout received",
    closeoutInAppHint: "Submitted by staff — open the log",
    openCloseoutInRegister: "View in log",
    dismissAlert: "Dismiss",
    dailyCloseoutAlertPrototype: "In-app owner alert when staff submit the daily summary",
    helpCenterTitle: "Help center",
    prototypeBuildLabel: "Prototype build",
    helpCenterBody: "This prototype covers daily closeout, outflow, log, reports, and notebook sharing. Use WhatsApp in settings for support.",
    prototypeDemoAccess: "Prototype demo",
    saveAccountSettings: "Save account details",
    shopName: "Shop name",
    renameStoreHint: "Changing the name does not affect previous operations or reports; all data remains linked to the same shop.",
    closeoutSetup: "Closeout setup",
    setupStore: "Shop to configure",
    storeSalesChannelScope: "Payment methods are configured independently for each shop and do not affect other shops.",
    visibleSalesChannels: "Payment methods shown to staff",
    manage: "Edit",
    outflowCategories: "Expense items",
    notebookAppearance: "Notebook appearance",
    notebookAppearanceDesc: "Notebook color for closeouts and reports",
    autoSavedAccount: "Saved automatically and applied to the notebook, reports, and sharing.",
    configure: "Manage",
    close: "Close",
    addPaymentMethod: "Add payment method",
    addSalesChannel: "Add sales channel",
    addIncomeSource: "Add custom item",
    customPaymentMethodName: "Custom payment method name",
    customSalesChannelName: "Custom sales channel name",
    customIncomeSourceName: "Custom item name",
    channelControlHint: "Disabled payment methods disappear from new entries but remain in historical reports.",
    stopChannel: "Disable",
    restoreChannel: "Restore",
    noSalesChannels: "No payment methods are enabled. Add or enable one first.",
    addCategory: "Add category",
    activeItemsHint: "Tap an item to show or hide it from entry screens.",
    teamMember: "Team member",
    addEmployee: "Add employee",
    employeeMobile: "Employee mobile number",
    employeeMobileMissing: "No login mobile configured yet",
    allowEntries: "Allow entries",
    billingDetails: "Subscription details",
    renewalDate: "Next renewal date",
    paymentMethod: "Payment method",
    contactSupport: "Contact support",
    whatsappSupport: "WhatsApp support",
    helpCenter: "Help center",
    activeChannels: "Active channels",
    activeCategories: "Active categories",
    changesSaved: "Changes saved",
    saveSettings: "Save changes",
    cancelChanges: "Cancel changes",
    saveToApplyTheme: "Select a style, then save to apply it to the notebook, reports, and sharing.",
    newEmployeeName: "Employee name",
    ownerNotifications: "Owner notifications",
    dailyCloseoutAlert: "Daily closeout received",
    dailyCloseoutAlertDesc: "Notify when staff submit the daily summary",
    teamAccess: "Staff and assigned shops",
    linkedStores: "Assigned shops",
    assignStores: "Select the shop or shops this employee can submit entries for",
    selectAtLeastOneStore: "Select at least one shop for this employee.",
    currentWorkStore: "Current entry shop",
    switchWorkStore: "Change shop",
    noAssignedStores: "No shop is assigned to this employee. Contact the owner.",
    employeeEntryOnly: "Employee access is fixed: entries only for assigned shops.",
    employeeCount: "1 employee can submit entries",
    manageEmployees: "Manage employees",
    subscription: "Subscription",
    subscriptionDetails: "Plan & subscription",
    subscriptionLoading: "Loading...",
    currentPlan: "Current plan",
    monthlyPrice: "Monthly price",
    planFeatures: "Plan features",
    upgradeOptions: "Upgrade options",
    requestUpgrade: "Request upgrade",
    upgradeSupportHint: "Upgrades are handled by support for now. Tap Request upgrade to open WhatsApp with a pre-filled message.",
    topPlanHint: "You are on the highest available plan. Contact support for custom changes.",
    retryLoad: "Try again",
    trialPlanBadge: "Trial",
    trialPlanTitle: "Free trial plan",
    trialPlanDescription: "15 days — up to 3 stores and 3 users. After the trial ends, upgrade to a paid plan to continue.",
    trialDaysRemaining: "Days remaining",
    trialEndsOn: "Trial ends on",
    upgradeToPaid: "Upgrade to paid",
    billingCycleLabel: "Billing cycle",
    renewalDaysRemaining: "Days until renewal",
    subscriptionExpiredTitle: "Subscription ended",
    subscriptionExpiredBody: "Your subscription period ended. Renew now to keep adding stores and employees.",
    subscriptionTrialExpiredBody: "Your free trial ended. Activate a paid plan to continue.",
    subscriptionGraceTitle: "Renewal grace period",
    subscriptionGraceBody: "Your subscription ended. You have {days} grace days before add-ons are blocked.",
    subscriptionRenewalSoon14: "Reminder: subscription ends in two weeks",
    subscriptionRenewalSoon7: "Reminder: subscription ends in one week",
    subscriptionRenewalSoon3: "Urgent: subscription ends soon",
    subscriptionRenewalSoonBody: "{days} days left — renew by {date}.",
    openSubscriptionDetails: "Subscription details",
    renewViaWhatsApp: "Renew via WhatsApp",
    allStores: "All",
    selectStore: "Select shop",
    searchStore: "Search shop or branch",
    viewStores: "View shops",
    hideStores: "Hide shops",
    storeResults: "Shop results",
    noActiveStores: "No active shops",
    combinedCloseout: "All shops",
    activeStoresScope: "All active shops",
    combinedReport: "All shops",
    store: "Shop",
    result: "Net",
    status: "Status",
    completed: "Completed",
    chooseStoreForDetails: "Select a shop to view attachments, details, or add outflow",
    shamiShort: "Shami",
    arzShort: "ARZ",
    shamiLocation: "Dhahran - Doha",
    arzLocation: "Khobar - Olaya",
    combinedTotal: "Total",
    loginTitle: "Sign in to Taqfeelah",
    loginSubtitle: "Track your shop closeout simply from your phone",
    loginGatewayTitle: "Welcome to Taqfeelah",
    loginGatewaySubtitle: "Choose owner or employee sign-in to continue",
    loginGatewayOwnerHint: "Reports, register, and store settings",
    loginGatewayEmployeeHint: "Daily closeout and operations entry",
    backToLoginGateway: "Back to sign-in choice",
    switchToEmployeeLogin: "Employee sign-in",
    switchToOwnerLogin: "Owner sign-in",
    switchPortalConfirmEmployee: "Your current session will end and you will go to employee sign-in.",
    switchPortalConfirmOwner: "Your current session will end and you will go to owner sign-in.",
    mobileNumber: "Mobile number",
    mobileHint: "A verification code will be sent — enter 05 or 5 format",
    sendCode: "Send verification code",
    verificationCode: "Verification code",
    codeSentTo: "Verification code sent to",
    verifyContinue: "Verify and continue",
    changeNumber: "Change number",
    phoneLoginOnly: "Current sign-in method: mobile number and secure verification code",
    linkedAccountNote: "Your linked account and permissions will open automatically",
    myStores: "My shops",
    activeStores: "Active shops",
    archivedStoresList: "Archived",
    showArchived: "Show archived",
    hideArchived: "Hide archived",
    noArchivedStores: "No archived shops",
    addStore: "Add shop",
    archiveStore: "Archive",
    archivedStore: "Archived",
    storeActive: "Active",
    addNewStore: "Add new shop",
    newStoreName: "New shop name",
    newStoreLocation: "Location or branch",
    archiveNotice: "Archiving stops new entries while retaining past closeouts and attachments.",
    confirmAddStore: "Save shop",
    delete: "Delete",
    deleteStore: "Delete shop",
    deleteChannel: "Hide payment method",
    deleteUser: "Delete user",
    confirmSafeDelete: "Confirm action",
    cancel: "Cancel",
    storeDeleteWithDataTitle: "A shop with records cannot be deleted",
    storeDeleteWithDataDesc: "This shop has previous closeouts or records. It will be archived and blocked from new entries only. Reports and attachments remain saved.",
    storeDeleteEmptyTitle: "Delete empty shop?",
    storeDeleteEmptyDesc: "This shop has no recorded data. It will be removed permanently from the list.",
    userDeleteTitle: "Remove user access?",
    userDeleteDesc: "The user's access will be disabled and removed from the active team. Their previous entries remain in the record.",
    channelDeleteTitle: "Disable payment method?",
    channelDeleteDesc: "The payment method will disappear from new entries, but remains in prior reports so historical figures are unaffected.",
    archiveAndKeepData: "Archive and keep data",
    deleteEmptyStore: "Delete empty shop",
    revokeAccess: "Remove access",
    retireChannel: "Disable channel",
    safeDeleteNotice: "Safe deletion preserves historical reports and records.",
    selectDay: "Select day",
    noEntriesDay: "No entries on this day",
    selectMonth: "Select month",
    selectYear: "Select year",
    selectRange: "Select range",
    year: "Year",
    custom: "Custom",
    applyPeriod: "Apply period",
    applyFilters: "Apply",
    resetFilters: "Reset",
    year2026: "2026",
    year2025: "2025",
    may2026: "May 2026",
    april2026: "April 2026",
    march2026: "March 2026",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    suggestedNextCloseout: "Suggested day based on the last saved closeout",
    changeDateAnytime: "You can change the date for a late entry or previous correction.",
    archivedReadOnly: "Archived â€” view only",
    viewPastReports: "View past reports",
    viewPastAttachments: "View previous log",
    atLeastOneCategory: "Keep at least one category available for new entries.",
    noActiveEmployee: "There is no active employee. Enable an employee from owner settings.",
    noCloseoutsPeriod: "No closeouts recorded for this period.",
    noSalesChannelsPeriod: "No payment methods recorded for this period.",
    noPaymentMethodsPeriod: "No payment methods",
    voided: "Voided",
    voidEntry: "Void entry",
    voidDialogTitle: "Void this entry?",
    voidConfirm: "This entry will be excluded from totals and reports while remaining in the log and attachments for reference.",
    voidReasonPrompt: "Void reason - optional",
    confirmVoid: "Confirm void",
    voidedByOwner: "Voided by owner",
    voidReason: "Void reason",
    duplicateSalesTitle: "A sales summary already exists",
    duplicateSalesWarning: "An active sales summary already exists for this shop on the same day. If you continue, this entry will be added to the total as a separate record and will not replace the earlier entry.",
    previousSalesEntries: "Current sales summaries",
    saveAdditionalEntry: "Save as additional entry",
    duplicateSalesOwnerAlert: "More than one sales summary was recorded for the same day",
    duplicateSalesOwnerHint: "Review the log to confirm the entries are valid and not duplicates.",
    openInLog: "Open log",
    approveMultipleSales: "Approve entries",
    approveMultipleSalesHint: "Confirm these multiple sales summaries are valid and dismiss this alert for the current entries.",
    restoreEntry: "Restore entry",
    restoreDialogTitle: "Restore this entry?",
    restoreConfirm: "This entry will be counted again in totals and reports while keeping its void and restore audit trail.",
    restoreReasonPrompt: "Restore reason - optional",
    confirmRestore: "Confirm restore",
    restored: "Restored",
    restoredByOwner: "Restored by owner",
    restoreReason: "Restore reason",
    saving: "Saving...",
    enterOwnerSummary: "Enter daily closeout",
    atLeastOneChannel: "Keep at least one payment method or sales channel available for sales entries.",
    stoppedChannels: "Disabled channels",
    noStoppedChannels: "No disabled channels.",
    invalidDateRange: "The start date must be before the end date.",
    archiveStoreTitle: "Archive shop?",
    archiveStoreDesc: "New entries will stop while all prior reports, logs, and attachments remain available.",
    confirmArchive: "Confirm archive",
    chooseStoreForSummary: "Select a shop before recording the closeout.",
    chooseStoreToStartEntry: "Select a shop to enable the entry fields",
    futureDateNotAllowed: "Transactions cannot be recorded for a future date.",
    closeoutRequiredForEntry: "Income or expense cannot be saved without a closeout. Open My Closeouts and start or select a closeout first.",
    auditTrail: "Activity log",
    actionCreated: "Created",
    actionVoided: "Voided",
    actionRestored: "Restored",
    actionReviewed: "Attachment reviewed",
    actionDuplicateApproved: "Multiple entries approved",
    channelsReport: "Channels report",
    daysReport: "Days report",
    attachmentsReport: "Attachments report",
    shopsComparisonReport: "Shops comparison",
    salesShort: "Sales",
    outflowShort: "Outflow",
    archiveStaffWarning: "Warning: the following employees will have no active shop for entries after archiving:",
    saveTeamChanges: "Save team access",
    desktopHeroTitle: "Your daily closeout notebook on your phone",
    desktopHeroDesc: "Record sales, outflow, and attachments, then follow daily shop movement clearly without accounting-system complexity.",
    ownerLogin: "Owner sign in",
    openOnMobile: "Open the app on your phone",
    qrPrototypeNote: "Prototype code â€” connected when the live version is deployed",
    fastEntryTitle: "Fast entry",
    fastEntryDesc: "Staff record daily sales and outflow in minutes.",
    clearFollowupTitle: "Clear follow-up",
    clearFollowupDesc: "Owners review movement and the log for every shop in one place.",
    proofLinkedTitle: "Linked proof",
    proofLinkedDesc: "Attach a photo to an operation when needed and review it later.",
    targetBusinessTitle: "Built for shops that need a simple daily closeout",
    targetBusinessDesc: "For restaurants, cafés, small shops, and lounges that need clear daily tracking without turning work into a full accounting system.",
    mobileFirstBadge: "Mobile-first",
    desktopOwnerLater: "Owner desktop dashboard is planned for later development",
    closeLogin: "Close sign in",
    desktopDemoStore: "Al Najah Restaurant",
    desktopDemoLocation: "Main branch",
  },
};

export default copy;
